name: Scheduled Notebook Execution
on:
  schedule:
    - cron: '0 3 * * *' # run at 2 AM UTC

jobs:
  ScheduledBuild:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_scheduled.yml@hellouniverse
